#ifndef PARAM_DEFAULTS_H
#define PARAM_DEFAULTS_H

//simulation parameters
#define AIRWAY_DEAD_SPACE_DEFAULT_LITRES 0.1
#define FRC_VOLUME_DEFAULT_LITRES 3.0
#define TIDAL_TIME_DEFAULT_SECONDS 5.0
#define TIDAL_VOLUME_DEFAULT_LITRES 1.0
#define BOLUS_START_VOL_DEFAULT_LITRES 0.5
#define BOLUS_DURATION_VOL_DEFAULT_LITRES 0.02
#define PLEURAL_PRESSURE_CHANGE_DEFAULT_CMH20 5.0
#define MOUTH_VOLUME_DEFAULT_LITRES 0
#define LUNG_ELASTANCE_DEFAULT_CMH20_PER_L 5.0
#define	BAG_RESISTANCE_DEFAULT_CMH20S_PER_L 0.25
#define	BAG_INERTANCE_DEFAULT_CMH20S2_PER_L 0
#define MOUTH_RESISTANCE_DEFAULT_CMH20S_PER_L 0.6
#define AIR_VISCOSITY_DEFAULT_CMH20S 1.93E-07
#define AIR_DENSITY_DEFAULT_KG_PER_M3 1.138
#define TIME_STEP_DEFAULT_SECONDS 0.01
#define MAX_FV_LENGTH_DEFAULT_MM 5.0
#define MIN_FV_PER_GEN_DEFAULT 2
#define MAX_ELEMENT_PE_DEFAULT 2
#define GAS_DIFFUSIVITY_DEFAULT_CM2_PER_S 0.105
#define WASHIN_END_DEFAULT_SECONDS 100.0
#define ACIN_FV_PER_GEN_DEFAULT 2
#define ACIN_SCALE_FACTOR_DEFAULT 0.123
#define ACIN_ASYMM_FACTOR_DEFAULT 0.254
#define ACIN_LR_RATIO_DEFAULT 4.0
#define PARTICLE_SIZE_DEFAULT_MM 0.00001
#define PARTICLE_DENSITY_DEFAULT_KG_PER_M3 997   //density of water
#define BOLTZMANN_CONSTANT 1.381E-23
#define BODY_TEMP_K 310.15
#define GRAV_ACCEL_MS2 9.81
#define BOLTZMANN_TEMP_VISCOSITY_DEFAULT_M3 2.235E-16 //Boltzmann constant * air temperature / air viscosity   (volume flux)
#define MEAN_FREE_PATH_DEFAULT_MM 66E-6

#define ACIN_HYBRID_GENSTART_AV_DEFAULT 0
#define ACIN_HYBRID_GENEND_AV_DEFAULT 0
#define GRAVITY_PRESSURE_GRADIENT_DEFAULT_CMH20_PER_MM 0.026  //pressure grad

#define PRINT_TIME_DEFAULT_SECONDS 5.0
#define BREATH_COUNT_DEFAULT 30

#define OUTPUT_PRECISION_DEFAULT 8

#endif
